import { cn } from "./cn";

/**
 * Inline LakeLens mark: sunlit-amber water drop with a moss leaf highlight over
 * spring-water waves on an ivory rounded square. Same art as public/icons/logo.svg
 * (generated by scripts/make-icons.mjs; keep the two in sync).
 */
export function Logo({ className, title }: { className?: string; title?: string }) {
  return (
    <svg
      viewBox="0 0 512 512"
      className={cn("size-10 shrink-0", className)}
      role={title ? "img" : undefined}
      aria-hidden={title ? undefined : "true"}
      focusable="false"
    >
      {title && <title>{title}</title>}
      <rect width="512" height="512" rx="112" fill="#f5f3ea" />
      <path d="M256 64c-48 70-100 130-100 192a100 100 0 0 0 200 0c0-62-52-122-100-192z" fill="#e08a2e" />
      <path d="M234 308c-12-48 18-92 66-102c4 48-18 92-66 102z" fill="#7a9a5b" />
      <path d="M240 302l56-92" fill="none" stroke="#f5f3ea" strokeWidth="7" strokeLinecap="round" />
      <path
        d="M40 400c36-28 72-28 108 0s72 28 108 0 72-28 108 0 72 28 108 0"
        fill="none"
        stroke="#3fb5c2"
        strokeWidth="26"
        strokeLinecap="round"
      />
      <path
        d="M40 452c36-28 72-28 108 0s72 28 108 0 72-28 108 0 72 28 108 0"
        fill="none"
        stroke="#cfeff2"
        strokeWidth="22"
        strokeLinecap="round"
      />
    </svg>
  );
}

/** Logo + "LakeLens" wordmark. Forest "Lake", spring-water "Lens" (both AA on ivory/white). */
export function Wordmark({ className, size = "md" }: { className?: string; size?: "md" | "lg" }) {
  return (
    <span className={cn("inline-flex items-center gap-2", className)}>
      <Logo className={size === "lg" ? "size-12" : "size-8"} />
      <span
        className={cn(
          "font-extrabold tracking-tight text-brown",
          size === "lg" ? "text-3xl" : "text-xl",
        )}
      >
        Lake<span className="text-cyan-deep">Lens</span>
      </span>
    </span>
  );
}
