import { cn } from "./cn";

const FOREST = "#1f4d3a";
const IVORY = "#f7f3e8";

const COIL = Array.from({ length: 8 }, (_, i) => {
  const t = i / 7;
  return { cx: 330 + t * 32, cy: 214 + t * 132 };
});

/**
 * The LakeLens mark: a fish springing out of the water on a coil, forest on ivory.
 *
 * Same art as public/icons/logo.svg (generated by scripts/make-icons.mjs; keep the two in
 * sync). Nothing here uses an element id, so two marks on one page cannot collide.
 */
export function Logo({ className, title }: { className?: string; title?: string }) {
  return (
    <svg
      viewBox="0 0 512 512"
      className={cn("size-10 shrink-0", className)}
      role={title ? "img" : undefined}
      aria-hidden={title ? undefined : "true"}
      focusable="false"
    >
      {title && <title>{title}</title>}
      <rect width="512" height="512" rx="112" fill={IVORY} />
      <path
        d="M0 352 C80 334 160 334 240 348 S420 362 512 344 L512 400 A112 112 0 0 1 400 512 L112 512 A112 112 0 0 1 0 400 Z"
        fill={FOREST}
      />
      <g fill="none" stroke={FOREST} strokeLinecap="round" strokeLinejoin="round">
        <path d="M120 90 C175 58 262 82 296 178 C230 170 165 150 120 90 Z" strokeWidth="15" />
        <path d="M187 104 Q193 128 172 141" strokeWidth="9" />
        <g strokeWidth="8.5">
          {COIL.map(({ cx, cy }) => (
            <ellipse key={cy} cx={cx} cy={cy} rx="26" ry="11" transform={`rotate(-10 ${cx} ${cy})`} />
          ))}
        </g>
      </g>
      <g fill={FOREST}>
        <circle cx="159" cy="99" r="8" />
        <path d="M214 80 Q252 74 274 95 Q256 96 244 104 Z" />
        <path d="M176 156 L197 190 Q199 172 207 163 Z" />
        <path d="M292 172 Q288 200 300 222 Q304 198 314 186 Z" />
        <path d="M290 174 Q322 168 346 190 Q322 188 304 192 Z" />
      </g>
      <g fill="none" stroke={IVORY} strokeLinecap="round" strokeWidth="6">
        <path d="M6 370 Q180 410 340 393 T496 378" strokeWidth="7" />
        <path d="M322 368 Q362 382 404 366" />
        <path d="M292 364 Q298 382 330 386" />
        <path d="M420 362 Q438 368 430 380" />
      </g>
      <rect x="3" y="3" width="506" height="506" rx="109" fill="none" stroke={FOREST} strokeOpacity="0.18" strokeWidth="6" />
    </svg>
  );
}

/** Logo plus the wordmark. Forest "Lake", spring-water "Lens" (both AA on ivory and white). */
export function Wordmark({ className, size = "md" }: { className?: string; size?: "md" | "lg" }) {
  return (
    <span className={cn("inline-flex items-center gap-2", className)}>
      <Logo className={size === "lg" ? "size-12" : "size-8"} />
      <span className={cn("font-extrabold tracking-tight text-brown", size === "lg" ? "text-3xl" : "text-xl")}>
        Lake<span className="text-cyan-deep">Lens</span>
      </span>
    </span>
  );
}
