import { cn } from "./cn";

/**
 * The LakeLens mark: a lens looking at water.
 *
 * A pale ivory ring on a forest tile, the lower half of the lens filled with spring water
 * under a single wave, and a small amber sun above the waterline. Same art as
 * public/icons/logo.svg (generated by scripts/make-icons.mjs; keep the two in sync).
 *
 * The water is drawn as a circle segment rather than a clipped rectangle, so two marks on
 * one page cannot collide over a shared element id.
 */
export function Logo({ className, title }: { className?: string; title?: string }) {
  return (
    <svg
      viewBox="0 0 512 512"
      className={cn("size-10 shrink-0", className)}
      role={title ? "img" : undefined}
      aria-hidden={title ? undefined : "true"}
      focusable="false"
    >
      {title && <title>{title}</title>}
      <rect width="512" height="512" rx="112" fill="#1f4d3a" />
      <circle cx="256" cy="248" r="118" fill="#1f4d3a" />
      <path d="M139 266 q29 -26 58 0 t58 0 t58 0 t58 0 A118 118 0 0 1 139 266 Z" fill="#3fb5c2" />
      <circle cx="303" cy="198" r="26" fill="#e08a2e" />
      <circle cx="256" cy="248" r="132" fill="none" stroke="#f5f3ea" strokeWidth="30" />
    </svg>
  );
}

/** Logo plus the wordmark. Forest "Lake", spring-water "Lens" (both AA on ivory and white). */
export function Wordmark({ className, size = "md" }: { className?: string; size?: "md" | "lg" }) {
  return (
    <span className={cn("inline-flex items-center gap-2", className)}>
      <Logo className={size === "lg" ? "size-12" : "size-8"} />
      <span className={cn("font-extrabold tracking-tight text-brown", size === "lg" ? "text-3xl" : "text-xl")}>
        Lake<span className="text-cyan-deep">Lens</span>
      </span>
    </span>
  );
}
